In [3]:
import numpy as np

### 1. What is a Python library? Why do we use Python libraries?

 - A Python library is a collection of functions and modules that extend the capabilities of Python programming language. These libraries are pre-written code that developers can use to perform specific tasks without having to write the code from scratch. Python libraries can range from general-purpose libraries like NumPy for numerical computing and Pandas for data manipulation to specialized libraries like TensorFlow for machine learning and Matplotlib for data visualization.

### 2. What is the difference between Numpy array and List?

NumPy arrays and Python lists are both used to store collections of data, but they have several differences:

 - Data Types: NumPy arrays are homogeneous, meaning all elements in the array must be of the same data type (e.g., integers, floats, etc.). In contrast, Python lists can contain elements of different data types.

 - Memory Efficiency: NumPy arrays are more memory efficient compared to Python lists. This is because NumPy arrays are stored in contiguous memory blocks, whereas Python lists are stored as a collection of pointers to separate objects.

 - Performance: NumPy arrays offer better performance for numerical operations compared to Python lists. This is because NumPy arrays are implemented in C, which allows for faster execution of mathematical operations. Additionally, NumPy provides optimized functions for array manipulation and mathematical operations.

- Functionality: NumPy arrays provide a wide range of mathematical functions and operations for array manipulation, such as element-wise operations, matrix operations, and statistical functions. Python lists do not offer built-in support for these operations, requiring developers to use loops or list comprehensions for similar functionality.

 - Indexing and Slicing: Both NumPy arrays and Python lists support indexing and slicing. However, NumPy arrays offer more advanced indexing capabilities, such as boolean indexing and fancy indexing, which allow for more flexible and efficient data manipulation.

### 3. Find the shape, size and dimension of the following array?

In [1]:
arr = [[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]

In [2]:
arr

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [5]:
print("The shape of the following array is: ", np.shape(arr))
print("The size of the following array is: ", np.size(arr))
print("The dimension of the following array is: ", np.ndim(arr))

The shape of the following array is:  (3, 4)
The size of the following array is:  12
The dimension of the following array is:  2


### 4. Write python code to access the first row of the following array?

In [6]:
arr = [[1, 2, 3, 4], 
       [5, 6, 7, 8],
       [9, 10, 11, 12]]

arr

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [8]:
print("The first row of the following array is:",arr[0])

The first row of the following array is: [1, 2, 3, 4]


### 5. How do you access the element at the third row and fourth column from the given numpy array?

In [9]:
arr = [[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]
arr

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [12]:
print("The the element at the third row and fourth column from the given numpy array is:", arr[2][3])

The the element at the third row and fourth column from the given numpy array is: 12


### 6. Write code to extract all odd-indexed elements from the given numpy array?

In [18]:
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
odd_arr = arr[arr % 2 != 0] 
print("Odd-indexed elements from the given numpy array are:",odd_arr)

Odd-indexed elements from the given numpy array are: [ 1  3  5  7  9 11]


### 7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [25]:
arr = np.random.rand(3,3)
arr

array([[0.47984349, 0.11164482, 0.49286332],
       [0.34066203, 0.37880683, 0.94615292],
       [0.78371126, 0.75618111, 0.8066855 ]])

### 8. Describe the difference between np.random.rand and np.random.randn?

*np.random.rand:*
Generates random numbers from a uniform distribution over the interval [0, 1).
Takes dimensions of the output array as arguments. For example, np.random.rand(3, 2) will generate a 3x2 array of random numbers.
Each number in the output array is generated independently and uniformly from the interval [0, 1).
All elements in the output array are positive.

In [26]:
arr1 = np.random.rand(3,3)

In [27]:
arr1

array([[0.33229451, 0.45611319, 0.39845564],
       [0.31877851, 0.46584545, 0.15200844],
       [0.70269573, 0.95629588, 0.74651478]])

*np.random.randn:*
Generates random numbers from a standard normal distribution (mean=0, standard deviation=1).
Takes dimensions of the output array as arguments, similar to np.random.rand.
Each number in the output array is drawn independently from a normal distribution with mean 0 and standard deviation 1.
The generated numbers can be positive or negative, and their distribution follows the bell-shaped curve of a standard normal distribution.

In [ ]:
arr2 = np.random.randn(3,3)

In [28]:
arr2

array([[-0.66499569,  0.7533573 , -0.48690184],
       [-0.8837031 ,  0.27844271, -1.10504218],
       [-1.22776238, -0.20632482, -0.5508913 ]])

### 9. Write code to increase the dimension of the following array?

In [30]:
arr = [[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]
arr

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [32]:
np.shape(arr)

(3, 4)

In [34]:
arr1 = np.resize(arr, (6,2))

In [35]:
arr1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [37]:
arr1.ndim

2

In [39]:
arr1.shape

(6, 2)

### 10. How to transpose the following array in NumPy?

In [44]:
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [45]:
arr_t = arr.T

In [46]:
arr_t

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

### 11. Consider the following matrix:

In [54]:
Matrix_A = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
Matrix_B = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [68]:
print("Index wise multiplication is:")
Matrix_A * Matrix_B

Index wise multiplication is:


array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [69]:
print("Matrix Multiplication is:")
np.matmul(Matrix_A, Matrix_B.T) # Tranpose Matrix_B to match dimensions

Matrix Multiplication is:


array([[ 30,  70, 110],
       [ 70, 174, 278],
       [110, 278, 446]])

In [70]:
print("Addition is:")
Matrix_A + Matrix_B

Addition is:


array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [71]:
print("Subtraction is:")
Matrix_B - Matrix_A

Subtraction is:


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [72]:
print("Division is:")
Matrix_B / Matrix_A

Division is:


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### 12. Which function in Numpy can be used to swap the byte order of an array?

In [73]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [74]:
arr.byteswap()

array([ 72057594037927936, 144115188075855872, 216172782113783808,
       288230376151711744, 360287970189639680, 432345564227567616])

### 13. What is the significance of the np.linalg.inv function?

In [79]:
arr = np.array([[1,2],[3,4]])
arr

array([[1, 2],
       [3, 4]])

In [80]:
np.linalg.inv(arr)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

### 14. What does the np.reshape function do, and how is it used?

- The np.reshape() function in NumPy is used to change the shape of an array without changing its data. It allows you to reorganize the elements of an array into a new shape, as long as the total number of elements remains the same. This function does not alter the original array; instead, it returns a new reshaped array.

In [81]:
arr

array([[1, 2],
       [3, 4]])

In [82]:
np.shape(arr)

(2, 2)

In [85]:
np.reshape(arr, (4,1))

array([[1],
       [2],
       [3],
       [4]])

### 15. What is broadcasting in Numpy?

 - Broadcasting in NumPy is a powerful mechanism that allows arrays with different shapes to be combined in arithmetic operations. When performing element-wise operations (such as addition, subtraction, multiplication, division, etc.) on arrays with different shapes, NumPy automatically broadcasts the arrays to make their shapes compatible.

In [86]:
arr = np.zeros((4,4))

In [87]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [88]:
row = np.array([1,2,3,4])

In [89]:
row

array([1, 2, 3, 4])

In [91]:
arr + row # row will get in each row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])